# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Sync certificates"
  lane :sync_certificates do
    match({readonly: true, type: "appstore"})
  end

  desc "Build the app (ipa)"
  lane :build do
    setup_ci
    sync_certificates
    increment_build_number(xcodeproj: "HospitalityDemo.xcodeproj")
    gym
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build
    pilot
  end
end
